[package]
name = "pro-man"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]

[dependencies]
toml = "0.3.*"
serde = "0.9"
serde_derive = "0.9"
clap = "*"
hyper = "0.10.*"
hyper-native-tls = "0.2.*"
